### ISSUE TITLE
Profile pic not working

### ISSUE THREAD

**Issue by Play-Real** [polonel/trudesk#104] opened 2018-11-09 03:23 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
Profile-pic broken link image on chrome for android V 70.0.3538.80 on mobile site
Does work on desktop chrome V 70.0.3538.77 on mobile site
Trudesk version 1.0.2 (docker image)

Trivial but still :)

**Comment by polonel** [comment] 2018-11-09 03:58
Can you post a screenshot of this so I know exactly which link is broken.
Are you referring to the account page?

**Comment by Play-Real** [comment] 2018-11-09 04:10
Sure, 
No I'm referring to the ticket overview page:
![screenshot_20181109-041016_chrome](https://user-images.githubusercontent.com/6843696/48242901-a298ca80-e3dd-11e8-8b19-6d0df3673306.jpg)

**Comment by Play-Real** [comment] 2018-11-09 04:10
Profile page has the same problem

**Comment by polonel** [comment] 2018-11-09 04:13
Does the web app (not mobile) show the correct picture? And if it does can
you try to re select the profile picture.

**Comment by Play-Real** [comment] 2018-11-09 04:32
(I use darkreader plugin so color scheme is different)
<img width="385" alt="mobile" src="https://user-images.githubusercontent.com/6843696/48243466-d9bcab00-e3e0-11e8-9775-694dbfbb10d4.png">

**Comment by polonel** [comment] 2018-11-09 04:33
Yea. I just confirmed it. Works fine on chrome desktop but not chrome mobile. I'm looking into what's going on. Thanks for the report.

**Comment by polonel** [comment] 2018-11-09 04:38
I found the issue. 
It has to do with a security update I pushed out to prevent access to asset files without a login session.

The reason it works on the desktop is that chrome has a valid login session already stored because of logging into the web app. If you log out of web app and refresh the mobile site (on the desktop) you'll notice the pictures no longer show.

Working on a fix...

**Comment by polonel** [comment] 2018-11-09 06:08
This has been fixed on `develop` and the nightly build on the docker image.

If you want to get it a test, switch your docker image to `polonel/trudesk:next` until the patch release is out.

**Comment by Play-Real** [comment] 2018-11-16 10:59
thnx ill test it as soon as possible

**Comment by Play-Real** [comment] 2018-11-23 00:36
It verks :)

**Closed** 2018-12-03 04:20 UTC
Labels: UI, bug, review, wontfix
