### ISSUE TITLE
Notification Not Working

### ISSUE THREAD

**Issue by aqilagit** [polonel/trudesk#495] opened 2022-04-18 14:04 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
No Notification appears on Agent / Admin Panel

**What did you expect to happen**:
Notification show red number on bell icon when new ticket submited or when new reply is submited or ticket status changed

**How to reproduce it (as minimally and precisely as possible)**:
Create New Ticket or Submit a reply on Ticket or change ticket status

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.2.0
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Node.JS Version: 16.14.2
- MongoDB Version: 5.0.7
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment] 2022-04-18 17:25
Are you the one entering the ticket? It doesn't send a notification to the person that put in the ticket.

**Comment by jazz7381** [comment] 2022-04-19 05:04
i have same problem

**Comment by aqilagit** [comment] 2022-04-19 05:31
> 

i have login both, as admin and as user with different user account and roles in 2 different google account / profile

As User : 
Login > Create Ticket > Success > i can hear notification sound but no notification appear on pannel

at the same time, i am login as Admin, and there is no notification appears on admin panel also.

**Comment by polonel** [comment] 2022-04-19 22:08
Confirmed. Working on a fix.

**Comment by polonel** [comment] 2022-04-21 02:33
Fix has been pushed to develop and will be included in the next release. Just to understand the issue, the notifications were indeed being created. They were just not displaying/updating the UI as intended.

**Closed** 2022-05-14 18:21 UTC
Labels: bug
