### ISSUE TITLE
Unable to connect Mailer and Mail Check

### ISSUE THREAD

**Issue by vaxo101** [polonel/trudesk#84] opened 2018-08-30 12:27 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ X ] BUG 
- [ ] FEATURE

**What happened**:
Email server was unable to connect
**What did you expect to happen**:
Email server to connect
**How to reproduce it (as minimally and precisely as possible)**:
using a domain name with an email server hosted by (for example) godaddy which uses altn names like *.prod.iad2.secureserver.net

**Anything else we need to know?**:
LOG

> 8/30 12:16:07 [9512] - warn:  Error: Hostname/IP doesn't match certificate's altnames: "Host: mydomain.com.au. is not in the cert's altnames: DNS:*.prod.iad2.secureserver.net, DNS:prod.iad2.secureserver.net"
    at Object.checkServerIdentity (tls.js:223:17)
    at TLSSocket.<anonymous> (_tls_wrap.js:1111:29)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
    at Socket.ondata (internal/wrap_js_stream.js:53:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

**Environment**:
- Trudesk Version: v1.0.0 (as defined in logs)
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Node.JS Version: v8.11.4
- MongoDB Version: MongoDB shell version v3.6.7
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment] 2018-08-30 17:29
I would need to see the certificate. According to the logs its not finding your domain inside the DNS entries for the certificate. If it doesn't find your domain inside the DNS entries it will mark the cert as invalid. This is not exclusive to the mailer used inside of Trudesk. Its rejecting the connection because "mydomain.com.au" does not fall into the two given DNS entries (*.prod.iad2.secureserver.net or prod.iad2.secureserver.net)

Can you also provide me with example mail settings you used to connect? Are you trying to connect to the mydomain.com.au domain or the prod.iad2.secureserver.net domain?

**Comment by vaxo101** [comment] 2018-08-31 01:10
Thanks for getting back to me, i am using the below details

> Mail server: mydomain.com
Port: 993
Username: support@mydomain.com

**Comment by vaxo101** [comment] 2018-09-02 08:55
@polonel Any update?

**Comment by polonel** [comment] 2018-09-03 03:38
@vaxo101 Apologize for the delay. I have yet to figure out what could cause this other than an SSL mismatch because the domain does not exist in the Subject Alt Names of the cert.

If you would like you could contact me privately at [Gitter](https://gitter.im/trudesk/support) or email me at polonel@trudesk.io

**Comment by polonel** [comment] 2018-09-15 18:34
After intense investigation and a major rewrite of the mail check module. I found no issues when connecting to a shared SSL cert site. I have set up multiple test sites on different providers (particular GoDaddy). 

I am closing this issue as I cannot reproduce. I also have not heard anything further so I will assume the issue you were having is resolved. I will reopen if need.

**Closed by polonel** 2018-09-15 18:34 UTC
Labels: investigate, wontfix
