### ISSUE TITLE
settings validation failed","message":"settings validation failed: value: Path value is required.

### ISSUE THREAD

**Issue by shivajimagadum15** [polonel/trudesk#196] opened 2019-05-03 10:08 UTC
I have deployed on a local machine. When I start the application and create the user from new database getting below error.
{"success":false,"error":{"errors":{"value":{"message":"Path `value` is required.","name":"ValidatorError","properties":{"message":"Path `value` is required.","type":"required","path":"value"},"kind":"required","path":"value"}},"_message":"settings validation failed","message":"settings validation failed: value: Path `value` is required.","name":"ValidationError"}}

![error_with_new_database_user_creation](https://user-images.githubusercontent.com/50233703/57131238-6c9b3880-6db9-11e9-88b5-233453862170.JPG)

**Comment by polonel** [comment] 2019-05-03 15:18
Duplicate of #192

**Closed by polonel** 2019-05-03 15:18 UTC
