### ISSUE TITLE
Cannot change color scheme

### ISSUE THREAD

**Issue by johncsuti** [polonel/trudesk#487] opened 2022-03-24 16:11 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: Changed color scheme to moonlight as i think it would look good then hit save reverts back to the default Light config.

**What did you expect to happen**: Color to be changed

**How to reproduce it (as minimally and precisely as possible)**: Changed color scheme to anything and it will not stay

**Anything else we need to know?**: Installed using the one line curl install. Already looked into caching and its not an issue.

**Environment**:
- Trudesk Version: 1.1.10
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4 LTS
- Node.JS Version: 12.22.10
- MongoDB Version: 4.4.12
- Is this hosted on cloud.trudesk.io: Nope

**Comment by polonel** [comment] 2022-03-25 22:58
Duplicate of #469

**Closed by polonel** 2022-03-25 22:58 UTC
