### ISSUE TITLE
mailCheck does not create Ticket when imap is set to AUTOTLS='always'

### ISSUE THREAD

**Issue by dataedgehungary** [polonel/trudesk#254] opened 2019-08-14 10:20 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:

I have two mail servers, both running on 143 port. One requires STARTTLS, the other one does not.

If I connect to the one without STARTTLS, then everything is working fine. 

If I want to connect to the server that requires STARTTLS, then the default configuration does not allow the authentication. I overcame this issue, adding 

  mailCheck.Imap = new Imap({
    user: MAILERCHECK_USER,
    password: MAILERCHECK_PASS,
    host: MAILERCHECK_HOST,
    port: MAILERCHECK_PORT,
    autotls: 'always'
  })

autotls: 'always' to the imap module (based on the module documentation)

Now the authentication is successful, and the server fetches then deletes the email from the inbox, logging:

8/14 11:42:18 [20192] - debug: Processed 1 Mail > Ticket

However, the ticket is not created...

I tried debugging as much as I could, seems like the handleMessages() function is never called. If I try to call it manually, then the messages.forEach() never... etc... so just a whole mess of problems but I guess there must be something with the autotls:'always' property.

I logged the message after mailCheck.messages.push(message) and it seems OK, with from=, subject=, body= all filled.

I even updated mailCheck.js from the develop fork with the update 6 days ago, but no luck... I guess it would not make a difference, because it was working properly without the autotls.

**What did you expect to happen**:

I expected to create the ticket from the STARTTLS IMAP server on port 143

**How to reproduce it (as minimally and precisely as possible)**:

add autotls: 'always' to mailCheck.Imap

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment] 2019-08-15 00:13
Duplicate of #251

**Closed by polonel** 2019-08-15 00:13 UTC
