### ISSUE TITLE
LDAP configuration

### ISSUE THREAD

**Issue by mhakim168** [polonel/trudesk#255] opened 2019-09-02 02:34 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x ] FEATURE

**What happened**: where's the LDAP configuration?

**What did you expect to happen**: I really hope this app can integrate to LDAP (microsoft or openldap)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: v1.0.14
- OS (e.g. from /etc/os-release): Centos 7
- Node.JS Version: v10.16.3
- MongoDB Version: v3.6.14
- Is this hosted on cloud.trudesk.io: no

**Comment by shahyar** [comment] 2019-09-02 06:30
Duplicate of #164

**Closed by shahyar** 2019-09-02 06:30 UTC
Labels: Planned (Cloud)
