### ISSUE TITLE
Crash when generating reports

### ISSUE THREAD

**Issue by rayediaz** [polonel/trudesk#106] opened 2018-11-13 15:13 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG
- [ ] FEATURE

**What happened**:
When I try to create a report, the app start loading and never finish. And when I check the console I find an error concerning with $document.createElement pops up.

**What did you expect to happen**:
I expect to get a report by user, groups, tags, etc.

**How to reproduce it (as minimally and precisely as possible)**:
Go to Generate, Select Report, Tickets by Groups, Users, Tags. 

**Anything else we need to know?**:

**Environment**:

- Trudesk Version: 1.0.2
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS (Bionic Beaver)
- Node.JS Version: 9.11.1
- MongoDB Version: 3.6.3
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment] 2018-11-13 15:15
Can you post the complete error that is reported in the console please?

**Comment by rayediaz** [comment] 2018-11-13 15:17
There you have! 

![error_reports](https://user-images.githubusercontent.com/15975670/48422702-99895f80-e735-11e8-8bd4-2971dcf07561.png)
![reports_error](https://user-images.githubusercontent.com/15975670/48422703-99895f80-e735-11e8-8146-501120a83ed5.png)

**Comment by polonel** [comment] 2018-11-13 15:19
Thanks. Working on fix.

**Comment by polonel** [comment] 2018-11-13 15:44
The issue is fixed on develop. I cannot push out a release yet. If you wish to switch to the develop branch for testing:
``` bash
> git checkout develop
> yarn
> yarn run build
```

Then restart the server under `PM2` or whichever method you used to run the server.

**Comment by rayediaz** [comment] 2018-11-13 15:56
Looking good! Thanks

**Closed** 2018-11-13 16:01 UTC
Labels: bug, in progress

**Comment by rajatency** [comment] 2023-08-28 07:40
Hi @polonel Is this fix merged into the main/master branch?
